// @license
// Copyright (c) ggsuite
//
// Use of this source code is governed by terms that can be
// found in the LICENSE file in the root of this package.

import 'dart:io';

import 'package:test/test.dart';

// GENERATED BY gg_version WriteVersionFile - DO NOT EDIT.
//
// Repairs the version literal in
// lib/src/gg_bridge_dart_side_version.dart
// when it drifts from pubspec.yaml. Drift is not an error here: the literal
// is rewritten and the test passes.

void main() {
  group('gg_bridge_dart_side_version.dart', () {
    test('matches the version in pubspec.yaml', () {
      const declaration = 'const String ggBridgeDartSideVersion = ';
      final match = RegExp(
        r'^version:\s*(\S+)\s*$',
        multiLine: true,
      ).firstMatch(File('pubspec.yaml').readAsStringSync());
      expect(match, isNotNull, reason: 'no version in pubspec.yaml');

      final expected = "$declaration'${match!.group(1)}';";
      final file = File('lib/src/gg_bridge_dart_side_version.dart');

      if (!file.readAsStringSync().contains(expected)) {
        file.writeAsStringSync(
          file.readAsStringSync().replaceFirst(
            RegExp("$declaration'[^']*';"),
            expected,
          ),
        );
      }

      expect(file.readAsStringSync(), contains(expected));
    });
  });
}
