name: gg_bridge_dart_side
description: gg_bridge_dart_side is the dart side of a dart - bridge - typescript repo trio.
version: 1.0.0
repository: https://github.com/ggsuite/gg_bridge_dart_side.git
publish_to: none

environment:
  sdk: ">=3.11.4 <4.0.0"

dependencies:
  path: ^1.9.1
  args: ^2.7.0
  gg_console_colors: ^2.1.5
  gg_process: ^1.1.6
  gg_args: ^2.0.4
  gg_log: ^1.0.6

dev_dependencies:
  gg_capture_print: ^1.0.9
  lints: ^6.1.0
  test: ^1.31.1

executables:
  gg_bridge_dart_side: bin/gg_bridge_dart_side.dart
